spring.application.name=solar-backend
spring.datasource.url=jdbc:mysql://localhost:3306/solar_db
spring.datasource.username=root
spring.datasource.password=deimulke

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true